/* ==========================================================================
   Rizos Ondea — Datos de la tienda
   ⚠️ CONFIGURACIÓN: cambia aquí el número de WhatsApp real del negocio.
   ========================================================================== */

const ONDEA_CONFIG = {
  // Número de WhatsApp en formato internacional SIN "+" (57 = Colombia).
  whatsapp: "573188546934",
  ciudad: "Villavicencio",
  envioNacional: 12000,      // COP — envío al resto de Colombia
  envioLocal: 6000,          // COP — envío dentro de Villavicencio
  envioGratisDesde: 150000,  // COP — umbral de envío gratis
};

/* Productos de ejemplo (inventados) mientras llega el catálogo real.
   Categorías: limpieza · hidratacion · definicion · accesorios · kits
   Tipos de rizo: ondulado (2A-2C) · rizado (3A-3C) · afro (4A-4C)

   🔌 INTEGRACIÓN DROPI: cuando cargues los productos reales, agrega a cada
   uno el campo  dropiId: "12345"  con el ID del producto en el catálogo de
   Dropi. Los pedidos que incluyan productos con dropiId podrán enviarse a
   Dropi desde el panel admin (o automáticamente con DROPI_AUTO_SEND). */
const ONDEA_PRODUCTS = [
  {
    id: "shampoo-low-poo",
    dropiId: null, // ej: "12345" — ID del producto en Dropi
    name: "Shampoo Low Poo «Onda Limpia»",
    category: "limpieza",
    categoryLabel: "Limpieza",
    types: ["ondulado", "rizado", "afro"],
    price: 42900,
    cost: 23500,
    size: "500 ml",
    rating: 4.8,
    reviews: 124,
    badge: "Esencial",
    badgeClass: "",
    art: "pump",
    short: "Limpieza suave sin sulfatos que respeta el aceite natural de tus rizos.",
    desc: "Shampoo de limpieza suave, libre de sulfatos y sales, formulado para el método curly. Limpia el cuero cabelludo sin resecar la fibra, dejando los rizos suaves, hidratados y listos para definir.",
    benefits: ["Libre de sulfatos, siliconas y parabenos", "Apto para método curly (CG friendly)", "Con aloe vera y agua de coco", "Uso frecuente: no reseca ni esponja"],
    howto: "Aplica sobre el cuero cabelludo húmedo, masajea con las yemas de los dedos y deja que la espuma limpie los largos al enjuagar. Repite si es necesario.",
    ingredients: "Agua, cocamidopropil betaína, aloe barbadensis, agua de coco, glicerina vegetal, pantenol, fragancia hipoalergénica.",
  },
  {
    id: "acondicionador-coco",
    name: "Acondicionador «Nutre & Desenreda» Coco y Karité",
    category: "hidratacion",
    categoryLabel: "Hidratación",
    types: ["ondulado", "rizado", "afro"],
    price: 44900,
    cost: 24900,
    size: "500 ml",
    rating: 4.9,
    reviews: 98,
    badge: null,
    art: "pump",
    short: "Desenreda al instante y aporta la humedad que tu rizo pide a gritos.",
    desc: "Acondicionador cremoso con aceite de coco y manteca de karité que facilita el desenredado, sella la humedad y devuelve la elasticidad a rizos y ondas.",
    benefits: ["Desenredado fácil sin romper el rizo", "Manteca de karité y aceite de coco", "Aporta brillo y elasticidad", "Sin siliconas insolubles"],
    howto: "Después del shampoo, aplica de medios a puntas, desenreda con los dedos o peine de dientes anchos y enjuaga con agua fría para sellar.",
    ingredients: "Agua, alcohol cetílico, manteca de karité, aceite de coco, behentrimonium metosulfato, pantenol, vitamina E.",
  },
  {
    id: "crema-define-rizos",
    name: "Crema para Peinar «Define Rizos»",
    category: "definicion",
    categoryLabel: "Definición",
    types: ["rizado", "afro"],
    price: 38900,
    cost: 19900,
    size: "300 ml",
    rating: 4.9,
    reviews: 156,
    badge: "Estrella ✦",
    badgeClass: "badge-pink",
    art: "tube",
    short: "Definición, control del frizz e hidratación en un solo paso.",
    desc: "Crema de peinado con fijación media que define el patrón natural del rizo, controla el frizz por hasta 48 horas y mantiene la hidratación sin dejar sensación grasosa ni efecto acartonado.",
    benefits: ["Define sin endurecer", "Anti-frizz hasta 48 h", "Con aceite de aguacate y proteína de arroz", "Protección de calor ligera"],
    howto: "Sobre cabello muy húmedo, aplica una cantidad tamaño moneda por sección, distribuye con praying hands y scrunch. Seca al aire o con difusor.",
    ingredients: "Agua, aceite de aguacate, proteína hidrolizada de arroz, glicerina, goma de linaza, manteca de mango, fragancia.",
  },
  {
    id: "gel-cristal",
    name: "Gel Fijador «Cristal de Rizos»",
    category: "definicion",
    categoryLabel: "Definición",
    types: ["ondulado", "rizado", "afro"],
    price: 35900,
    cost: 17900,
    size: "250 ml",
    rating: 4.7,
    reviews: 87,
    badge: null,
    art: "jarGel",
    short: "Fijación fuerte con acabado brillante y cero residuo blanco.",
    desc: "Gel de fijación fuerte que forma un cast protector alrededor de cada rizo para una definición duradera. Se rompe fácil con scrunch y no deja escamas ni residuo blanco.",
    benefits: ["Fijación fuerte de larga duración", "Cast fácil de romper (SOTC)", "Con linaza y pantenol", "No deja residuo ni descama"],
    howto: "Aplica sobre el cabello empapado después de tu crema, con praying hands y scrunch. Cuando seque al 100 %, rompe el cast con un poco de aceite en las manos.",
    ingredients: "Agua, extracto de linaza, glicerina, pantenol, goma xantana, conservante ecocert, fragancia suave.",
  },
  {
    id: "duo-rizos-definidos",
    dropiId: "1977942", // ID en el catálogo de Dropi (proveedor LIVANA COLOMBIA SAS)
    name: "Dúo Rizos Definidos «Milagros»",
    category: "hidratacion",
    categoryLabel: "Hidratación",
    types: ["ondulado", "rizado", "afro"],
    price: 85000,
    cost: 64090,
    size: "2 tratamientos × 450 ml",
    rating: 4.9,
    reviews: 0,
    badge: "Nuevo",
    badgeClass: "",
    art: "jar",
    images: [
      "Statics/productos/duo-rizos-definidos/1.webp",
      "Statics/productos/duo-rizos-definidos/2.webp",
      "Statics/productos/duo-rizos-definidos/3.jpg",
    ],
    short: "Bio Repolarizador + Nutrición y Crecimiento: tratamiento intensivo que define, repara y fortalece tus rizos.",
    desc: "El Dúo Rizos Definidos de Milagros combina dos tratamientos de alto desempeño: el Bio Repolarizador Capilar (450 ml — pro vitamina B5, keratina, aceite de argán, pulpa de coco y vitamina E) que repara la fibra y aporta brillo intenso, y la Terapia Nutrición y Crecimiento (450 ml — mantequilla de mango, complejo botánico de aminoácidos y vitamina E) que fortalece la hebra, reduce la caída y mejora la definición natural. Juntos hidratan profundamente, controlan el frizz y estimulan el crecimiento. Ideal para rizos secos, frágiles o con procesos químicos; apto para todo tipo de rizo. Dermatológicamente comprobados.",
    benefits: ["Hidratación profunda sin apelmazar", "Repara el daño y aporta brillo intenso", "Fortalece la hebra y reduce la caída", "Mejora la definición y evita la porosidad y el frizz", "Estimula el crecimiento del cabello"],
    howto: "Mezcla 2 cucharadas de cada tratamiento, aplica sobre cabello húmedo de raíz a puntas y distribuye con los dedos o un peine de dientes anchos cubriendo cada rizo. Deja actuar 15-30 minutos, enjuaga con abundante agua y lava con tu shampoo de preferencia. Úsalo 1-2 veces por semana.",
    ingredients: "Extractos naturales de plantas, proteínas vegetales y complejos hidratantes con aminoácidos esenciales. Bio Repolarizador: pro vitamina B5, keratina, aceite de argán, pulpa de coco y vitamina E. Nutrición y Crecimiento: mantequilla de mango, complejo botánico de aminoácidos y vitamina E. Uso externo; evitar el contacto con los ojos.",
  },
  {
    id: "aceite-argan",
    name: "Aceite Sellador «Brillo de Argán»",
    category: "hidratacion",
    categoryLabel: "Hidratación",
    types: ["ondulado", "rizado", "afro"],
    price: 39900,
    cost: 18500,
    size: "60 ml",
    rating: 4.8,
    reviews: 64,
    badge: null,
    art: "dropper",
    short: "Mezcla ligera de argán y jojoba para sellar, brillar y romper el cast.",
    desc: "Blend de aceites puros de argán y jojoba de rápida absorción. Sella la hidratación, aporta brillo espejo y es perfecto para romper el cast del gel sin generar frizz.",
    benefits: ["Argán y jojoba 100 % puros", "Sella puntas y evita resequedad", "Brillo sin efecto grasoso", "Ideal para SOTC y retoques"],
    howto: "Aplica 2-4 gotas en las palmas y sella de medios a puntas sobre cabello húmedo o seco. Úsalo también para romper el cast del gel.",
    ingredients: "Aceite de argán, aceite de jojoba, vitamina E, aceite esencial de vainilla.",
  },
  {
    id: "leave-in-rizos-vivos",
    name: "Leave-In «Rizos Vivos»",
    category: "hidratacion",
    categoryLabel: "Hidratación",
    types: ["ondulado", "rizado"],
    price: 36900,
    cost: 18900,
    size: "250 ml",
    rating: 4.7,
    reviews: 59,
    badge: null,
    art: "spray",
    short: "Hidratación diaria sin enjuague para refrescar y revivir tus rizos.",
    desc: "Crema ligera sin enjuague que hidrata, desenreda y protege durante el día. Perfecta para el refresh de rizos entre lavados: revive la definición sin apelmazar.",
    benefits: ["Hidratación diaria sin enjuague", "Ideal para refresh entre lavados", "Protege del sol y la humedad", "Fórmula ligera: no apelmaza"],
    howto: "En cabello húmedo o seco, aplica una pequeña cantidad y scrunch para reactivar el rizo. Úsalo a diario o en tu rutina de refresh.",
    ingredients: "Agua, aloe vera, glicerina, aceite de almendras, pantenol, filtro UV, fragancia suave.",
  },
  {
    id: "espuma-onda-ligera",
    name: "Espuma Voluminizadora «Onda Ligera»",
    category: "definicion",
    categoryLabel: "Definición",
    types: ["ondulado"],
    price: 33900,
    cost: 16900,
    size: "200 ml",
    rating: 4.6,
    reviews: 41,
    badge: "Para ondas",
    badgeClass: "",
    art: "foam",
    short: "Volumen y definición con acabado natural para ondas 2A-2C.",
    desc: "Mousse ultraligera creada para cabello ondulado: define la onda, levanta la raíz y aporta cuerpo sin el peso de las cremas densas. Acabado flexible y natural.",
    benefits: ["Diseñada para ondas 2A-2C", "Volumen desde la raíz", "Acabado flexible, no acartona", "Con proteína de trigo"],
    howto: "Sobre cabello húmedo boca abajo, aplica 2-3 pumps de espuma con scrunch desde las puntas hacia la raíz. Seca con difusor para máximo volumen.",
    ingredients: "Agua, proteína de trigo, pantenol, polímeros de fijación flexible, fragancia.",
  },
  {
    id: "kit-rizos-la-pocion",
    dropiId: "1893635", // ID en el catálogo de Dropi (SKU KIT-00085, proveedor LIVANA COLOMBIA SAS)
    name: "Kit para Rizos Tongolé «La Poción»",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado"],
    price: 176600,
    cost: 129865,
    size: "4 productos",
    rating: 5.0,
    reviews: 0,
    badge: "Envío gratis",
    badgeClass: "badge-pink",
    art: "kit",
    images: [
      "Statics/productos/kit-rizos-la-pocion/1.jpeg",
      "Statics/productos/kit-rizos-la-pocion/2.jpeg",
      "Statics/productos/kit-rizos-la-pocion/3.jpeg",
      "Statics/productos/kit-rizos-la-pocion/4.jpeg",
      "Statics/productos/kit-rizos-la-pocion/5.jpeg",
      "Statics/productos/kit-rizos-la-pocion/6.jpeg",
      "Statics/productos/kit-rizos-la-pocion/7.jpeg",
    ],
    short: "Shampoo + tratamiento + crema para peinar + mascarilla Tongolé: el sistema completo para rizos 2A a 3C.",
    desc: "El sistema completo para hidratar, definir y restaurar ondas, rizos y crespos (2A a 3C) con acabado natural y libre de frizz. Incluye Shampoo Tongolé (450 ml), Tratamiento Tongolé (450 ml), Crema para Peinar Tongolé (450 ml) y Mascarilla Capilar Tongolé (350 ml): fórmulas nutritivas que reparan la fibra capilar, controlan el frizz y logran rizos definidos por más tiempo, sin sensación pesada.",
    benefits: ["Define y realza ondas y rizos de forma natural", "Controla el frizz incluso en climas húmedos", "Hidratación profunda sin apelmazar", "Repara y fortalece la fibra capilar", "Ideal para cabellos ondulados, rizados y crespos (2A a 3C)"],
    howto: "Lava con el Shampoo Tongolé, aplica el Tratamiento y enjuaga. Usa la Mascarilla 1-2 veces por semana dejándola actuar 10-15 minutos. Finaliza con la Crema para Peinar sobre cabello húmedo y define con tus manos o tu técnica preferida.",
    ingredients: "Consulta la etiqueta de cada producto Tongolé incluido en el kit.",
  },
  {
    id: "gorro-saten",
    name: "Gorro de Satén «Buenas Noches, Rizos»",
    category: "accesorios",
    categoryLabel: "Accesorios",
    types: ["ondulado", "rizado", "afro"],
    price: 25900,
    cost: 9900,
    size: "Talla única",
    rating: 4.9,
    reviews: 203,
    badge: null,
    art: "bonnet",
    short: "Protege tu definición mientras duermes y amanece con rizos intactos.",
    desc: "Gorro de satén premium con banda elástica cómoda que no marca la frente. Evita el frizz y la fricción con la almohada para que tu definición dure más días.",
    benefits: ["Satén suave de alta calidad", "Elástico cómodo que no aprieta", "Reduce frizz y quiebre nocturno", "Alarga la vida de tu definición"],
    howto: "Recoge tus rizos en piña (pineapple) y cúbrelos con el gorro antes de dormir. Lávalo a mano cada semana.",
    ingredients: "95 % satén de poliéster, 5 % elastano.",
  },
  {
    id: "toalla-microfibra",
    name: "Toalla de Microfibra «Seca sin Frizz»",
    category: "accesorios",
    categoryLabel: "Accesorios",
    types: ["ondulado", "rizado", "afro"],
    price: 29900,
    cost: 12500,
    size: "60 × 40 cm",
    rating: 4.8,
    reviews: 88,
    badge: null,
    art: "towel",
    short: "Absorbe el exceso de agua sin alterar el patrón de tu rizo.",
    desc: "Toalla de microfibra ultra absorbente y suave que retira el exceso de agua con plopping o scrunch sin generar frizz ni deformar el rizo, a diferencia de la toalla de algodón.",
    benefits: ["Microfibra ultra suave", "Ideal para plopping", "Seca más rápido sin frizz", "Con botón para sujetarla"],
    howto: "Después de aplicar tus productos, haz scrunch suave o envuelve el cabello en plopping por 10-15 minutos antes de difusar.",
    ingredients: "80 % poliéster, 20 % poliamida (microfibra).",
  },
  {
    id: "difusor-universal",
    name: "Difusor Universal Plegable",
    category: "accesorios",
    categoryLabel: "Accesorios",
    types: ["ondulado", "rizado", "afro"],
    price: 45900,
    cost: 22900,
    size: "Universal",
    rating: 4.6,
    reviews: 35,
    badge: null,
    art: "diffuser",
    short: "Seca con volumen y definición; se pliega para viajar.",
    desc: "Difusor de silicona plegable que se adapta a casi cualquier secadora. Distribuye el aire de forma uniforme para secar tus rizos con volumen, definición y sin frizz. Perfecto para viajes.",
    benefits: ["Compatible con la mayoría de secadoras", "Silicona plegable: ocupa mínimo espacio", "Secado uniforme sin frizz", "Dedos largos para levantar la raíz"],
    howto: "Ajústalo a tu secadora, usa temperatura media y seca por secciones llevando el rizo hacia la raíz. Termina con aire frío para fijar.",
    ingredients: "Silicona de grado alimenticio resistente al calor.",
  },
  {
    id: "kit-rizos-lavado-etniker",
    dropiId: "1979862", // ID en el catálogo de Dropi (SKU KIT-00079, proveedor LIVANA COLOMBIA SAS)
    name: "Kit Rizos Lavado Etniker",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado", "afro"],
    price: 99000,
    cost: 65000,
    size: "3 productos",
    rating: 4.9,
    reviews: 0,
    badge: "Nuevo",
    badgeClass: "",
    art: "kitSmall",
    images: [
      "Statics/productos/kit-rizos-lavado-etniker/1.webp",
      "Statics/productos/kit-rizos-lavado-etniker/2.jpg",
      "Statics/productos/kit-rizos-lavado-etniker/3.jpg",
      "Statics/productos/kit-rizos-lavado-etniker/4.jpg",
    ],
    short: "Shampoo + crema para peinar + gel definidora Etniker: tu wash day en 3 pasos (limpia, hidrata, define).",
    desc: "Tu wash day en 3 pasos con Etniker Afro Hair Care: limpia con el Shampoo (250 ml — a elegir entre Nutritivo o Limpieza Profunda anti-residuos), hidrata con la Crema para Peinar Curl Defining (290 g, coco, karité y monoï de Tahití) y define con la Gel Definidora de Rizos (300 g, coco y linaza). Acabado natural, brillo y cero frizz, sin rigidez ni residuos. Ideal para texturas 2B a 4C y cabellos en transición. Escríbenos en las notas del pedido cuál shampoo prefieres; si no nos dices, enviamos el Nutritivo.",
    benefits: ["Definición y moldeo con fijación flexible", "Control del frizz y brillo sin residuos ni pegajosidad", "Hidratación y desenredo sin tirones", "Rutina simple: limpia → hidrata → define", "Fórmulas sin sulfatos, sin siliconas y sin parabenos"],
    howto: "1) Limpia con el shampoo: el Nutritivo para uso frecuente, o el de Limpieza Profunda máximo 2 veces al mes. 2) En cabello húmedo aplica la crema por secciones y activa con scrunch; no enjuagues. 3) Distribuye la gel por secciones, haz scrunch de abajo hacia arriba y seca al aire o con difusor en calor bajo. Refresh día 2-3: humedece ligeramente y aplica una microdosis de gel.",
    ingredients: "Gel: coco y linaza. Crema: coco, karité y monoï de Tahití (con filtro UV). Fórmulas sin sulfatos, sin sal añadida, sin siliconas, sin aceite mineral y libres de parabenos. Uso externo; evitar contacto con los ojos.",
  },
];
