/* ==========================================================================
   Rizos Ondea — Datos de la tienda
   ⚠️ CONFIGURACIÓN: cambia aquí el número de WhatsApp real del negocio.
   ========================================================================== */

const ONDEA_CONFIG = {
  // Número de WhatsApp en formato internacional SIN "+" (57 = Colombia).
  whatsapp: "573188546934",
  ciudad: "Villavicencio",
  envioNacional: 12000,      // COP — envío al resto de Colombia
  envioLocal: 6000,          // COP — envío dentro de Villavicencio
  envioGratisDesde: 150000,  // COP — umbral de envío gratis
};

/* Catálogo real, conectado a Dropi.
   Categorías activas: hidratacion · definicion · accesorios · kits
   (limpieza sigue vacía; al agregar shampoos sueltos, restaura su chip en
   productos.html y su tarjeta en index.html)
   Tipos de rizo: ondulado (2A-2C) · rizado (3A-3C) · afro (4A-4C)

   🔌 INTEGRACIÓN DROPI: cada producto lleva  dropiId  con su ID del
   catálogo de Dropi y  cost  con el precio del proveedor. Fotos en
   Statics/productos/<id>/ (la 1 es la principal). */
const ONDEA_PRODUCTS = [
  {
    id: "duo-rizos-definidos",
    dropiId: "1977942", // ID en el catálogo de Dropi (proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Dúo Rizos Definidos «Milagros»",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado", "afro"],
    price: 94900,
    cost: 64090,
    size: "2 tratamientos × 450 ml",
    rating: 4.9,
    reviews: 0,
    badge: "Nuevo",
    badgeClass: "",
    art: "jar",
    images: [
      "Statics/productos/duo-rizos-definidos/1.webp",
      "Statics/productos/duo-rizos-definidos/2.webp",
      "Statics/productos/duo-rizos-definidos/3.jpg",
    ],
    short: "Bio Repolarizador + Nutrición y Crecimiento: tratamiento intensivo que define, repara y fortalece tus rizos.",
    desc: "El Dúo Rizos Definidos de Milagros combina dos tratamientos de alto desempeño: el Bio Repolarizador Capilar (450 ml — pro vitamina B5, keratina, aceite de argán, pulpa de coco y vitamina E) que repara la fibra y aporta brillo intenso, y la Terapia Nutrición y Crecimiento (450 ml — mantequilla de mango, complejo botánico de aminoácidos y vitamina E) que fortalece la hebra, reduce la caída y mejora la definición natural. Juntos hidratan profundamente, controlan el frizz y estimulan el crecimiento. Ideal para rizos secos, frágiles o con procesos químicos; apto para todo tipo de rizo. Dermatológicamente comprobados.",
    benefits: ["Hidratación profunda sin apelmazar", "Repara el daño y aporta brillo intenso", "Fortalece la hebra y reduce la caída", "Mejora la definición y evita la porosidad y el frizz", "Estimula el crecimiento del cabello"],
    howto: "Mezcla 2 cucharadas de cada tratamiento, aplica sobre cabello húmedo de raíz a puntas y distribuye con los dedos o un peine de dientes anchos cubriendo cada rizo. Deja actuar 15-30 minutos, enjuaga con abundante agua y lava con tu shampoo de preferencia. Úsalo 1-2 veces por semana.",
    ingredients: "Extractos naturales de plantas, proteínas vegetales y complejos hidratantes con aminoácidos esenciales. Bio Repolarizador: pro vitamina B5, keratina, aceite de argán, pulpa de coco y vitamina E. Nutrición y Crecimiento: mantequilla de mango, complejo botánico de aminoácidos y vitamina E. Uso externo; evitar el contacto con los ojos.",
  },
  {
    id: "kit-curl-boost-etniker",
    dropiId: "2020761", // ID en el catálogo de Dropi (SKU KIT-00092, proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit Curl Boost Etniker",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado", "afro"],
    price: 129900,
    cost: 71900,
    size: "3 productos + estuche",
    rating: 4.9,
    reviews: 0,
    badge: "Nuevo",
    badgeClass: "",
    art: "kitSmall",
    images: [
      "Statics/productos/kit-curl-boost-etniker/1.png",
      "Statics/productos/kit-curl-boost-etniker/2.jpg",
      "Statics/productos/kit-curl-boost-etniker/3.jpg",
      "Statics/productos/kit-curl-boost-etniker/4.jpg",
    ],
    short: "Crema + Jelly Gel + Hydroelixir Etniker: definición flexible, brillo intenso y cero frizz, sin peso.",
    desc: "El kit de estilizado exprés de Etniker Afro Hair Care para realzar la forma natural del rizo. Incluye la Crema para Peinar Curl Defining (290 g — hidrata y prepara el rizo como base de estilizado), el Gel Fluido Jelly Gel (300 g — define, moldea y fija con brillo, sin acartonar) y el Hydroelixir (38 ml — aceite ligero que sella la hidratación y controla el frizz), más un estuche/llavero Etniker para llevar tus esenciales. Con coco, karité, monoï de Tahití y linaza: hidratación profunda sin sensación pesada. Ideal para wash & go, twist out y el refresh diario, en rizos 2C a 4A.",
    benefits: ["Definición flexible desde la raíz hasta las puntas", "Brillo intenso sin efecto graso", "Control del frizz incluso en clima húmedo", "Hidratación ligera que no aplasta el rizo", "Incluye estuche/llavero Etniker de regalo"],
    howto: "1) Sobre cabello limpio y húmedo, aplica la Crema para Peinar por secciones. 2) Encima aplica el Jelly Gel y define con las manos o con rake & shake. 3) Finaliza con unas gotas del Hydroelixir para sellar puntas y dar brillo (o úsalo al día siguiente para el refresh). Tip: mezcla crema + gel para una definición personalizada.",
    ingredients: "Coco, karité, monoï de Tahití y linaza. Sin sal, sin sulfatos, sin parabenos; gel sin alcohol ni residuos. Uso externo.",
  },
  {
    id: "kit-curl-define-etniker",
    dropiId: "2020544", // ID en el catálogo de Dropi (SKU 7701256542387, proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit Curl Define Etniker",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado", "afro"],
    price: 119900,
    cost: 63078,
    size: "3 productos + cepillo",
    rating: 4.9,
    reviews: 0,
    badge: "Nuevo",
    badgeClass: "",
    art: "kitSmall",
    images: [
      "Statics/productos/kit-curl-define-etniker/1.png",
      "Statics/productos/kit-curl-define-etniker/2.jpg",
      "Statics/productos/kit-curl-define-etniker/3.jpg",
      "Statics/productos/kit-curl-define-etniker/4.jpg",
    ],
    short: "Shampoo + mascarilla + gel definidor Etniker con cepillo profesional: hidratación y definición duradera.",
    desc: "La rutina para recuperar la hidratación, suavidad y definición de rizos y afros. Incluye el Shampoo Coco & Karité (250 ml — limpia suavemente sin resecar), la Mascarilla Deep Conditioner (300 g — coco, karité y mango que reparan y fortalecen), el Curl Defining Gel (300 g — fijación suave-media que activa el rizo sin rigidez) y el Cepillo Profesional Etniker para definir por mechones. Hidratación profunda, mejor elasticidad y frizz bajo control, con rizos definidos, brillantes y con movimiento natural. Ideal para rizos 2C a 3C y afros 4A a 4C, en cabello natural, en transición o procesado.",
    benefits: ["Hidratación profunda para rizos secos o maltratados", "Definición flexible y duradera, sin rigidez", "Nutrición intensiva con coco, karité y mango", "Control del frizz incluso en clima húmedo", "Incluye cepillo profesional de definición"],
    howto: "1) Lava con el Shampoo 2-3 veces por semana. 2) Aplica la Mascarilla de medios a puntas 10-15 minutos y enjuaga (en rizos tipo 4 puedes dejar un poco como crema). 3) Sobre cabello húmedo aplica el Gel Definidor y define por mechones con el Cepillo Etniker (rake & shake, twist out o shingling). 4) Seca con difusor o al aire. Tip: reactiva al día siguiente con agua en atomizador.",
    ingredients: "Coco, karité, manteca de mango y linaza. Sin sal, sin sulfatos, sin parabenos. Uso externo.",
  },
  {
    id: "kit-hydracurl-etniker",
    dropiId: "2020507", // ID en el catálogo de Dropi (SKU KIT-00093, proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit Hydracurl Etniker",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado", "afro"],
    price: 139900,
    cost: 87617,
    size: "4 productos + cepillo",
    rating: 4.9,
    reviews: 0,
    badge: "Nuevo",
    badgeClass: "",
    art: "kit",
    images: [
      "Statics/productos/kit-hydracurl-etniker/1.png",
      "Statics/productos/kit-hydracurl-etniker/2.jpg",
      "Statics/productos/kit-hydracurl-etniker/3.jpg",
      "Statics/productos/kit-hydracurl-etniker/4.jpg",
      "Statics/productos/kit-hydracurl-etniker/5.jpg",
    ],
    short: "Limpieza profunda + hidratación intensa + espuma definidora, con cepillo profesional Etniker incluido.",
    desc: "La rutina completa para revivir rizos secos, opacos o deshidratados. Incluye el Shampoo Limpieza Profunda (250 ml — purifica y retira acumulación), la Mascarilla Deep Conditioner (300 g — coco, karité y manzanilla que nutren y reparan), el Hydroelixir (38 ml — aceite que sella la hidratación y controla el frizz), la Espuma Intensificadora de Rizos (150 ml — açaí, linaza y ácido hialurónico para definir sin peso, con protección térmica) y el Cepillo Profesional Etniker para activar y definir el rizo por mechones. Ideal para rizos 2B a 3C, afros 4A a 4C y cabellos en transición — apto para niñas, mujeres y hombres.",
    benefits: ["Limpieza profunda que retira residuos y acumulación", "Hidratación intensiva: más elasticidad y suavidad", "Espuma definidora ligera con ácido hialurónico", "Incluye cepillo profesional de definición", "Ideal para transición capilar y rizos sin forma"],
    howto: "1) Lava con el Shampoo Limpieza Profunda (1-2 veces por semana). 2) Aplica la Mascarilla 10-15 minutos y enjuaga. 3) Sella medios y puntas con el Hydroelixir. 4) Define con la Espuma sobre cabello húmedo. 5) Activa el rizo por mechones con el Cepillo Etniker inclinándolo hacia afuera. Tip: mezcla una gota de Hydroelixir con la espuma para más brillo.",
    ingredients: "Coco, karité, manzanilla, açaí, linaza, ácido hialurónico y aceites nutritivos. Sin sal ni parabenos. Uso externo.",
  },
  {
    id: "kit-emergencia-reparacion-milagros",
    dropiId: "1977270", // ID en el catálogo de Dropi (SKU KIT-00035, proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit Emergencia y Reparación «Milagros»",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado", "afro"],
    price: 149900,
    cost: 106193,
    size: "4 productos",
    rating: 4.9,
    reviews: 0,
    badge: "Nuevo",
    badgeClass: "",
    art: "kit",
    images: [
      "Statics/productos/kit-emergencia-reparacion-milagros/1.webp",
      "Statics/productos/kit-emergencia-reparacion-milagros/2.webp",
      "Statics/productos/kit-emergencia-reparacion-milagros/3.webp",
      "Statics/productos/kit-emergencia-reparacion-milagros/4.webp",
      "Statics/productos/kit-emergencia-reparacion-milagros/5.webp",
    ],
    short: "La rutina intensiva de rescate para cabello dañado: shampoo + 3 tratamientos reparadores Milagros.",
    desc: "La solución de choque para cabello dañado, quebradizo o sin brillo por tintes, decoloraciones o plancha. Incluye el Shampoo Emergencia Capilar (450 ml), el Tratamiento Bio Repolarizador Capilar (450 ml), el Tratamiento Emergencia Capilar (450 ml) y la ampolleta Rescate Instantáneo «El Experto en Rescate» (30 ml). Sus activos —biotina, colágeno hidrolizado, queratina vegetal, provitamina B5, pulpa de coco y vitamina E— reparan la fibra desde el interior, fortalecen la raíz y estimulan un crecimiento saludable. Dermatológicamente comprobados.",
    benefits: ["Repara el daño de tintes, decoloración y calor", "Fortalece la raíz y reduce la caída", "Devuelve brillo, suavidad y elasticidad", "Resultados visibles desde la primera aplicación", "Rutina completa de reconstrucción en 4 pasos"],
    howto: "Mezcla una ampolleta del Rescate Instantáneo con la misma cantidad de agua hasta lograr textura cremosa; añade una dosis del Bio Repolarizador y una del Tratamiento Emergencia y revuelve. Aplica sobre cabello seco o ligeramente húmedo de medios a puntas (evita el cuero cabelludo), deja actuar 30 minutos —con gorro térmico se potencia— y lava con el Shampoo Emergencia. Úsalo 1-2 veces por semana.",
    ingredients: "Biotina y colágeno hidrolizado, provitamina B5 y queratina vegetal, pulpa de coco y vitamina E, extractos naturales y aminoácidos. Uso externo; evitar el contacto con los ojos.",
  },
  {
    id: "kit-crecimiento-antifrizz-milagros",
    dropiId: "2019484", // ID en el catálogo de Dropi (SKU KIT-00074, proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit Crecimiento Antifrizz «Milagros»",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado", "afro"],
    price: 169900,
    cost: 113724,
    size: "3 productos",
    rating: 4.9,
    reviews: 0,
    badge: "Envío gratis",
    badgeClass: "badge-pink",
    art: "kit",
    images: [
      "Statics/productos/kit-crecimiento-antifrizz-milagros/1.png",
      "Statics/productos/kit-crecimiento-antifrizz-milagros/2.webp",
      "Statics/productos/kit-crecimiento-antifrizz-milagros/3.webp",
    ],
    short: "Shampoo + acondicionador con cebolla y péptidos + mascarilla profesional: crecimiento, menos caída y cero frizz.",
    desc: "La rutina profesional de Milagros para estimular el crecimiento, reducir el frizz y reparar el cabello dañado. Incluye el Shampoo Crecimiento con extracto de cebolla y péptidos (450 ml) que restaura la fuerza y despierta el crecimiento desde la raíz, el Acondicionador Antifrizz fortalecedor (450 ml) que desenreda al instante y previene la caída por quiebre, y la Mascarilla Reparación Intensiva Milagros Professional (450 ml) que revierte el daño por decoloración, tinturas y calor. Cabello más fuerte, suave, manejable y con menos caída — apto para hombres y mujeres, y para uso frecuente.",
    benefits: ["Estimula el crecimiento con extracto de cebolla y péptidos", "Controla el frizz y facilita el desenredo", "Repara el daño por tintes, decoloración y calor", "Fortalece la fibra y reduce la caída por quiebre", "Resultados que se potencian en 3-6 semanas de constancia"],
    howto: "Lava con el Shampoo Crecimiento masajeando el cuero cabelludo (3-5 veces por semana). Aplica el Acondicionador Antifrizz de medios a puntas, deja actuar 2-5 minutos y enjuaga. Usa la Mascarilla Reparación Intensiva 1-2 veces por semana, dejándola actuar 15-20 minutos antes de enjuagar.",
    ingredients: "Extracto de cebolla morada, péptidos fortalecedores, cafeína, activos antifrizz y componentes reparadores con aminoácidos. Uso externo; evitar el contacto con los ojos.",
  },
  {
    id: "kit-definicion-antifrizz-ponto",
    dropiId: "2176373", // ID en el catálogo de Dropi (SKU KIT-00076, proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit Definición Antifrizz Ponto",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado"],
    price: 174900,
    cost: 116177,
    size: "4 productos",
    rating: 4.9,
    reviews: 0,
    badge: "Envío gratis",
    badgeClass: "badge-pink",
    art: "kit",
    images: [
      "Statics/productos/kit-definicion-antifrizz-ponto/1.png",
      "Statics/productos/kit-definicion-antifrizz-ponto/2.jpeg",
      "Statics/productos/kit-definicion-antifrizz-ponto/3.jpeg",
      "Statics/productos/kit-definicion-antifrizz-ponto/4.jpeg",
      "Statics/productos/kit-definicion-antifrizz-ponto/5.jpeg",
    ],
    short: "Limpieza suave, 3 en 1 hidratante, espuma definidora y el termoprotector Boom: ondas sin frizz de principio a fin.",
    desc: "La rutina Ponto completa para ondas y rizos con limpieza suave, hidratación, definición y control del frizz. Incluye el Shampoo Suave Aloe Vera (300 ml — con agua micelar, limpia sin resecar), el Tratamiento 3 en 1 Mi Dulce Pelo «Soy Ondulada» (380 ml — sirve como mascarilla, acondicionador o crema para peinar), el Termoprotector Boom (que protege del calor del secador, difusor, plancha o rizador mientras controla el frizz) y la Espuma Definidora Suspiros (90 ml — define, da volumen y mantiene el movimiento natural). Fórmulas sin sulfatos, parabenos ni siliconas.",
    benefits: ["Limpieza suave con aloe vera y agua micelar", "3 en 1: mascarilla, acondicionador o crema para peinar", "Termoprotector para difusor, secador o plancha", "Espuma que define y da volumen sin rigidez", "Sin sulfatos, parabenos ni siliconas"],
    howto: "1) Lava con el Shampoo Suave Aloe Vera masajeando el cuero cabelludo y enjuaga. 2) Aplica el Tratamiento 3 en 1 de medios a puntas, como acondicionador, mascarilla o crema según lo que tu cabello pida. 3) Aplica el Termoprotector Boom de medios a puntas, especialmente antes del calor. 4) Finaliza con la Espuma Suspiros sobre cabello húmedo, moldea con las manos y seca al aire o con difusor.",
    ingredients: "Aloe vera y agua micelar (shampoo). Fórmulas sin sulfatos, sin parabenos y sin siliconas. Consulta las etiquetas para la lista completa. Uso externo.",
  },
  {
    id: "kit-rizos-kids-leche-pal-pelo",
    dropiId: "2103656", // ID en el catálogo de Dropi (SKU KIT-00082, proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit Rizos Kids Leche pal Pelo",
    category: "kits",
    categoryLabel: "Kits",
    types: ["rizado", "afro"],
    price: 149900,
    cost: 88296,
    size: "3 productos",
    rating: 4.9,
    reviews: 0,
    badge: "Nuevo",
    badgeClass: "",
    art: "kit",
    images: [
      "Statics/productos/kit-rizos-kids-leche-pal-pelo/1.png",
      "Statics/productos/kit-rizos-kids-leche-pal-pelo/2.png",
      "Statics/productos/kit-rizos-kids-leche-pal-pelo/3.png",
      "Statics/productos/kit-rizos-kids-leche-pal-pelo/4.png",
    ],
    short: "La rutina completa para los rizos de los peques: shampoo + acondicionador + crema de peinar, suaves y sin irritar.",
    desc: "La rutina Leche pal Pelo diseñada especialmente para cuidar y definir el cabello rizado de niñas y niños. Incluye el Shampoo Hidratante Kids Rizos (440 ml — limpia con suavidad sin resecar), el Acondicionador Rizos Perfectos (440 ml — desenreda y nutre) y la Crema de Peinar Control Rizos (440 ml — define los rizos y controla el frizz todo el día). Sus fórmulas con aceite de argán, leche de avena, leche de coco y proteína de trigo hidratan profundamente, fortalecen la fibra capilar y facilitan el peinado diario sin causar irritación. El aliado perfecto para que la hora del peinado deje de ser una batalla.",
    benefits: ["Diseñado especialmente para el cabello rizado infantil", "Define y controla los rizos de forma natural", "Hidratación profunda que reduce el frizz", "Facilita el desenredado y el peinado diario", "Fórmulas suaves con ingredientes de origen natural"],
    howto: "1) Aplica el Shampoo sobre el cabello húmedo, masajea suavemente y enjuaga. 2) Aplica el Acondicionador de medios a puntas, deja actuar unos minutos y enjuaga. 3) Termina con la Crema de Peinar sobre cabello húmedo o seco para definir los rizos y controlar el frizz. Ideal para la rutina diaria antes del cole.",
    ingredients: "Aceite de argán (nutre y da brillo), leche de avena (suavidad e hidratación), leche de coco (fortalece y protege) y proteína de trigo (mejora la estructura capilar). Uso externo; evitar el contacto con los ojos.",
  },
  {
    id: "kit-rescate-nutritivo-milagros",
    dropiId: "2127615", // ID en el catálogo de Dropi (SKU KIT-00031, proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit Rescate Nutritivo «Milagros»",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado", "afro"],
    price: 179900,
    cost: 125810,
    size: "4 productos",
    rating: 4.9,
    reviews: 0,
    badge: "Envío gratis",
    badgeClass: "badge-pink",
    art: "kit",
    images: ["Statics/productos/kit-rescate-nutritivo-milagros/1.png"],
    short: "Shampoo + tratamiento + mascarilla + leave-in Milagros: la rutina completa que recupera, nutre y da brillo.",
    desc: "La rutina completa de recuperación capilar de Milagros para cabello maltratado por químicos, calor o decoloración. Incluye el Shampoo Bio-repolarizador (450 ml) que limpia mientras reconstruye la fibra, el Tratamiento Bio Repolarizador Capilar (450 ml) que repara e hidrata con protección UV, la Mascarilla Multivitamínica con aminoácidos (450 ml) que fortalece y ayuda a reducir la caída, y el Tratamiento Magia Capilar sin enjuague (150 ml) que controla el frizz, hidrata las puntas y da brillo inmediato durante el día. Resultados visibles desde las primeras aplicaciones.",
    benefits: ["Reparación profunda del daño por químicos, calor o decoloración", "Hidratación intensiva y nutrición completa", "Reduce el frizz y las puntas secas", "Cabello más fuerte, brillante y sedoso", "Incluye leave-in para mantener el resultado todo el día"],
    howto: "Lava con el Shampoo Bio-repolarizador y aplica el Tratamiento Bio Repolarizador de medios a puntas; enjuaga. Usa la Mascarilla Multivitamínica 1-2 veces por semana dejándola actuar 15-20 minutos. Finaliza con el Magia Capilar sin enjuague sobre cabello húmedo o seco para controlar el frizz y sellar las puntas.",
    ingredients: "Bio-repolarizadores con pro vitamina B5, keratina, aceite de argán, pulpa de coco y vitamina E; mascarilla con multivitaminas y aminoácidos; Magia Capilar con ácido hialurónico, extracto de lino, aceite de sacha inchi y vitaminas A, B5 y H. Uso externo.",
  },
  {
    id: "kit-reconstruccion-rizos-pocion",
    dropiId: "2013217", // ID en el catálogo de Dropi (SKU 7536851254598, proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit Reconstrucción de Rizos «Tongolé × R3START Plex»",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado"],
    price: 239900,
    cost: 169578,
    size: "5 productos",
    rating: 5.0,
    reviews: 0,
    badge: "Envío gratis",
    badgeClass: "badge-pink",
    art: "kit",
    images: [
      "Statics/productos/kit-reconstruccion-rizos-pocion/1.png",
      "Statics/productos/kit-reconstruccion-rizos-pocion/2.png",
      "Statics/productos/kit-reconstruccion-rizos-pocion/3.png",
      "Statics/productos/kit-reconstruccion-rizos-pocion/4.png",
      "Statics/productos/kit-reconstruccion-rizos-pocion/5.jpg",
      "Statics/productos/kit-reconstruccion-rizos-pocion/6.png",
    ],
    short: "La rutina Tongolé completa + R3START Plex: reconstrucción molecular para rizos dañados o sin forma.",
    desc: "El sistema para reparar, fortalecer y revivir rizos dañados, débiles o sin forma. Combina la hidratación y definición de Tongolé — Shampoo (450 ml), Tratamiento (450 ml), Mascarilla Capilar (350 ml) y Crema para Peinar (450 ml) — con la reconstrucción avanzada del Tratamiento Constructor R3START Plex (100 ml), una tecnología molecular que repara la fibra desde adentro, sella la cutícula y reduce el quiebre con cada aplicación. Devuelve elasticidad, suavidad y vitalidad desde la primera semana. Ideal para rizos 2A a 3C que pasaron por tintes, decoloración, plancha o procesos químicos.",
    benefits: ["Reconstrucción molecular con R3START Plex", "Restaura la elasticidad de rizos sin vida o sin forma", "Reduce el quiebre y fortalece la hebra", "Hidratación profunda con control del frizz", "Definición con acabado natural y movimiento"],
    howto: "Lava con el Shampoo Tongolé, aplica el Tratamiento y enjuaga. Usa la Mascarilla 1-2 veces por semana. Aplica el R3START Plex de medios a puntas sobre cabello húmedo o seco, sin enjuagar. Finaliza definiendo con la Crema para Peinar Tongolé.",
    ingredients: "Línea Tongolé con aceites naturales; R3START Plex con tecnología de reconstrucción molecular que construye y mejora los enlaces del cabello. Consulta las etiquetas para la lista completa. Uso externo.",
  },
  {
    id: "kit-pre-decoloracion-pocion",
    dropiId: "2013612", // ID en el catálogo de Dropi (SKU 795486215936, proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit Pre Decoloración «La Poción»",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado", "afro"],
    price: 249900,
    cost: 175206,
    size: "5 productos",
    rating: 5.0,
    reviews: 0,
    badge: "Envío gratis",
    badgeClass: "badge-pink",
    art: "kit",
    images: [
      "Statics/productos/kit-pre-decoloracion-pocion/1.png",
      "Statics/productos/kit-pre-decoloracion-pocion/2.png",
      "Statics/productos/kit-pre-decoloracion-pocion/3.png",
      "Statics/productos/kit-pre-decoloracion-pocion/4.png",
      "Statics/productos/kit-pre-decoloracion-pocion/5.png",
      "Statics/productos/kit-pre-decoloracion-pocion/6.png",
    ],
    short: "Prepara tu cabello ANTES de decolorar o tinturar: fortalece, protege y minimiza el daño del químico.",
    desc: "El kit de preparación para procesos químicos: fortalece la estructura interna del cabello antes de una decoloración o tintura para minimizar la rotura y el quiebre. Incluye la Mascarilla Ancestral (350 ml — vitaminas A, B1, B2, B6, B12, C y E), el Shampoo Acondicionador Refrescante (450 ml), el Tratamiento Reestructurante R3START PLEX (100 ml — aminoácidos y proteínas que refuerzan los puentes internos de la fibra), el Óleo B8 Brillo Infinito y el Bite Me Banano (250 ml — suplemento antioxidante hidroreparador). Sella la cutícula, reduce la porosidad, equilibra el pH y deja el cabello listo para soportar el proceso químico conservando elasticidad y resistencia.",
    benefits: ["Fortalece la fibra ANTES del proceso químico", "Minimiza el daño, la rotura y el quiebre", "R3START PLEX: refuerzo tipo plex con aminoácidos y proteínas", "Sella la cutícula y reduce la porosidad", "Equilibra el pH y facilita el desenredo posterior"],
    howto: "En los días previos al proceso: lava con el Shampoo Acondicionador Refrescante y aplica la Mascarilla Ancestral sobre cabello húmedo el tiempo recomendado. En días alternos usa el R3START PLEX para fortalecer los puentes internos. Una vez por semana aplica el Bite Me Banano como pre-shampoo desintoxicante. Sella de medios a puntas con el Óleo B8.",
    ingredients: "Mascarilla Ancestral con vitaminas A, B1, B2, B6, B12, C y E; R3START PLEX con aminoácidos y proteínas; Bite Me con extracto de banano; Óleo B8 con mezcla de aceites vegetales. Uso externo.",
  },
  {
    id: "kit-rizos-largos-abundantes",
    dropiId: "2207916", // ID en el catálogo de Dropi (SKU KIT-00039, proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit Rizos Largos y Abundantes «Tongolé»",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado"],
    price: 229900,
    cost: 158358,
    size: "6 productos",
    rating: 5.0,
    reviews: 0,
    badge: "Envío gratis",
    badgeClass: "badge-pink",
    art: "kit",
    images: [
      "Statics/productos/kit-rizos-largos-abundantes/1.png",
      "Statics/productos/kit-rizos-la-pocion/3.jpeg",
      "Statics/productos/kit-rizos-la-pocion/4.jpeg",
      "Statics/productos/kit-rizos-la-pocion/5.jpeg",
    ],
    short: "La rutina Tongolé completa + tónicos Oxy y Energy: hidratación, definición y crecimiento en 6 pasos.",
    desc: "El sistema para conseguir rizos definidos, hidratados, más largos y con volumen natural. Combina la nutrición profunda de Tongolé — Shampoo (450 ml), Tratamiento (450 ml), Crema para Peinar (450 ml) y Mascarilla Capilar (350 ml) — con el poder estimulante de los tónicos Poción: Oxy Tonic (40 ml, diurno, oxigena y revitaliza la raíz) y Energy Tonic (40 ml, nocturno, estimula el crecimiento). Fortalece la raíz, mejora el crecimiento y potencia la forma natural del rizo sin frizz ni pesadez. Ideal para texturas 2A a 3C que buscan crecer sanas, fuertes y con abundancia.",
    benefits: ["Activa el crecimiento y fortalece la raíz", "Hidratación profunda sin apelmazar", "Rizos más abundantes, definidos y con movimiento", "Reduce el frizz y sella la cutícula", "Evita el quiebre y la caída por debilitamiento"],
    howto: "Lava con el Shampoo Tongolé, aplica el Tratamiento y enjuaga. Usa la Mascarilla 1-2 veces por semana. Aplica el Oxy Tonic de día y el Energy Tonic de noche directamente en el cuero cabelludo. Define con la Crema para Peinar sobre cabello húmedo.",
    ingredients: "Consulta la etiqueta de cada producto Tongolé y de los tónicos Oxy y Energy incluidos en el kit. Uso externo.",
  },
  {
    id: "kit-fortalece-hidrata-pocion",
    dropiId: "1888742", // ID en el catálogo de Dropi (SKU KIT-00044, proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit Fortalece e Hidrata «La Poción»",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado", "afro"],
    price: 184900,
    cost: 133682,
    size: "4 productos",
    rating: 4.9,
    reviews: 0,
    badge: "Envío gratis",
    badgeClass: "badge-pink",
    art: "kit",
    images: [
      "Statics/productos/kit-fortalece-hidrata-pocion/1.jpeg",
      "Statics/productos/kit-fortalece-hidrata-pocion/2.png",
      "Statics/productos/kit-fortalece-hidrata-pocion/3.png",
      "Statics/productos/kit-fortalece-hidrata-pocion/4.png",
      "Statics/productos/kit-fortalece-hidrata-pocion/5.png",
    ],
    short: "Nutrición, reparación y fortaleza: la rutina Poción de 4 pasos para cabello seco, opaco o maltratado.",
    desc: "El sistema para restaurar, hidratar y fortalecer el cabello desde la raíz hasta las puntas. Incluye el Shampoo La Poción (450 ml — limpieza nutritiva que protege), el Tratamiento Renovador (450 ml — nutrición intensiva para cabellos secos o dañados), la Mascarilla Ancestral (350 ml — rica en vitaminas A, B1, B2, B6, B12, C y E) y la Crema para Peinar Dual (450 ml — control, suavidad y definición sin peso). Repara el daño químico, reduce la ruptura y el frizz, y devuelve brillo natural sin sensación grasa. Apto para todo tipo de cabello, incluidos rizados y procesados.",
    benefits: ["Repara cabello maltratado o con daño químico", "Nutre desde la fibra interna hasta la cutícula", "Fortalece la hebra: menos ruptura y frizz", "Brillo natural sin sensación grasa", "Rutina completa de 4 pasos con crema para peinar incluida"],
    howto: "Lava con el Shampoo La Poción. Aplica el Tratamiento Renovador de medios a puntas y enjuaga. Usa la Mascarilla Ancestral 2-3 veces por semana dejándola actuar 10-15 minutos. Finaliza con la Crema para Peinar sobre cabello húmedo o seco, y peina como prefieras.",
    ingredients: "Mascarilla Ancestral con vitaminas A, B1, B2, B6, B12, C y E. Consulta la etiqueta de cada producto Poción del kit para la lista completa. Uso externo.",
  },
  {
    id: "kit-rizos-perfectos-pocion",
    dropiId: null, // ⚠️ PENDIENTE: falta el ID de Dropi (SKU KIT-00025) — sin él este kit no viaja automático a Dropi
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit Rizos Perfectos «Tongolé»",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado", "afro"],
    price: 189900,
    cost: 134011,
    size: "4 productos",
    rating: 4.9,
    reviews: 0,
    badge: "Envío gratis",
    badgeClass: "badge-pink",
    art: "kit",
    images: [
      "Statics/productos/kit-rizos-perfectos-pocion/1.png",
      "Statics/productos/kit-rizos-perfectos-pocion/2.png",
      "Statics/productos/kit-rizos-perfectos-pocion/3.jpg",
      "Statics/productos/kit-rizos-perfectos-pocion/4.png",
      "Statics/productos/kit-rizos-perfectos-pocion/5.png",
    ],
    short: "La rutina Tongolé con gel definidor: limpia, nutre, peina y fija tus rizos con acabado natural.",
    desc: "La rutina completa de definición Tongolé, de la limpieza al acabado final. Incluye el Shampoo Tongolé (450 ml — limpia suavemente mientras hidrata), la Mascarilla Tongolé (350 ml — repara y fortalece la fibra con mayor elasticidad), la Crema de Peinar Tongolé (450 ml — leave-in que desenreda y controla el frizz) y el Gel Definidor Tongolé (moldeador que fija y mantiene la forma de ondas y rizos). Controla el frizz, mejora la elasticidad y mantiene los rizos definidos por más tiempo, con acabado suave y con movimiento. ¿Prefieres tratamiento en vez de gel? Mira el Kit para Rizos Tongolé «La Poción».",
    benefits: ["Limpia sin resecar e hidrata a profundidad", "Define ondas y rizos de forma natural", "Controla el frizz y facilita el peinado diario", "Gel definidor que fija sin acartonar", "Suavidad, elasticidad y brillo"],
    howto: "1) Lava con el Shampoo Tongolé y enjuaga. 2) Aplica la Mascarilla de medios a puntas, deja actuar unos minutos y enjuaga. 3) Sobre cabello húmedo aplica la Crema de Peinar para hidratar y desenredar. 4) Termina con el Gel Definidor para moldear y fijar la forma de tus rizos.",
    ingredients: "Consulta la etiqueta de cada producto Tongolé incluido en el kit. Uso externo.",
  },
  {
    id: "kit-milagro-herbal",
    dropiId: "1979509", // ID en el catálogo de Dropi (SKU KIT-00055, proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit Milagro Herbal «Milagros»",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado", "afro"],
    price: 194900,
    cost: 139288,
    size: "4 productos",
    rating: 4.9,
    reviews: 0,
    badge: "Envío gratis",
    badgeClass: "badge-pink",
    art: "kit",
    images: [
      "Statics/productos/kit-milagro-herbal/1.jpg",
      "Statics/productos/kit-milagro-herbal/2.webp",
      "Statics/productos/kit-milagro-herbal/3.webp",
      "Statics/productos/kit-milagro-herbal/4.webp",
      "Statics/productos/kit-milagro-herbal/5.webp",
    ],
    short: "Romero, jengibre, canela y eucalipto: crecimiento, control de grasa y menos caída desde la raíz.",
    desc: "El poder de los extractos naturales para un cabello fuerte, fresco y con crecimiento saludable. Incluye el Shampoo Milagro Herbal (450 ml — con ramas de romero y jengibre 100% naturales, eficacia seborreguladora clínicamente comprobada), el Acondicionador Milagro Herbal (450 ml — desenreda y disminuye la caída), la Mascarilla Capilar Milagro Herbal (450 g — con provitamina B5, keratina y péptidos de avena) y el Tónico Revitalizante (110 ml — fortalece los folículos y purifica el cuero cabelludo). Ideal para cabello graso, con caída o debilitado que necesita limpieza profunda sin resecar.",
    benefits: ["Estimula el crecimiento con romero y jengibre", "Regula el exceso de grasa del cuero cabelludo", "Disminuye la caída y fortalece la raíz", "Nutre y repara sin sensación grasosa", "Con extractos 100% naturales y eficacia comprobada"],
    howto: "Antes del lavado, aplica el Tónico sobre el cuero cabelludo seco, masajea y déjalo actuar mínimo 2 horas (o toda la noche). Lava con el Shampoo dejando actuar 3-5 minutos y enjuaga. Aplica el Acondicionador de medios a puntas 5 minutos y retira con agua fría. Usa la Mascarilla 1-2 veces por semana, 15-30 minutos.",
    ingredients: "Romero y jengibre (crecimiento y raíz fuerte), canela y eucalipto (regulan la grasa), extracto de arroz y aminoácidos, provitamina B5, keratina, péptidos de avena y vitaminas naturales. Uso externo; evitar el contacto con los ojos.",
  },
  {
    id: "kit-secado-ondas-sonadas",
    dropiId: "2013522", // ID en el catálogo de Dropi (SKU 733654185498, proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit Secado y Ondas Soñadas «La Poción»",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado"],
    price: 199900,
    cost: 129379,
    size: "4 productos",
    rating: 4.9,
    reviews: 0,
    badge: "Envío gratis",
    badgeClass: "badge-pink",
    art: "kit",
    images: [
      "Statics/productos/kit-secado-ondas-sonadas/1.png",
      "Statics/productos/kit-secado-ondas-sonadas/2.png",
      "Statics/productos/kit-secado-ondas-sonadas/3.png",
      "Statics/productos/kit-secado-ondas-sonadas/4.png",
      "Statics/productos/kit-secado-ondas-sonadas/5.png",
    ],
    short: "La rutina para ondas con calor sin daño: protección térmica hasta 232 °C, reparación y brillo espejo.",
    desc: "El kit para quienes modelan sus ondas con blower, plancha o tenaza sin sacrificar la salud del cabello. Incluye Bite Me Banano (250 ml — suplemento capilar antioxidante hidroreparador con extracto de banano y aceites de macadamia y aguacate), Shampoo Reparación (450 ml), Termoprotector Capilar B8 (protege hasta 450 °F / 232 °C, con complejo de ceramidas) y el Óleo B8 Brillo Infinito que sella las puntas con efecto espejo. Previene el daño térmico, repara la fibra, controla el frizz y permite styling frecuente sin quiebre.",
    benefits: ["Protección térmica real hasta 232 °C (450 °F)", "Repara la fibra y evita el quiebre por calor", "Brillo con efecto espejo y control del frizz", "Puntas selladas con el Óleo B8", "Permite modelar el cabello con frecuencia sin dañarlo"],
    howto: "Aplica Bite Me como pre-shampoo para desintoxicar. Lava con el Shampoo Reparación y enjuaga. Vuelve a usar Bite Me como acondicionador, deja actuar y enjuaga. Sobre el cabello húmedo aplica el Termoprotector antes del blower, plancha o tenaza. Finaliza con unas gotas del Óleo B8 para brillo y control del frizz.",
    ingredients: "Bite Me: extracto de banano, aceites de macadamia y aguacate. Termoprotector: complejo de ceramidas y siliconas volátiles. Óleo B8: mezcla de aceites vegetales selladores. Uso externo.",
  },
  {
    id: "kit-reparacion-profunda-pocion",
    dropiId: "2012557", // ID en el catálogo de Dropi (SKU KIT-00043, proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit Reparación Profunda «La Poción»",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado", "afro"],
    price: 219900,
    cost: 154667,
    size: "5 productos",
    rating: 5.0,
    reviews: 0,
    badge: "Envío gratis",
    badgeClass: "badge-pink",
    art: "kit",
    images: [
      "Statics/productos/kit-reparacion-profunda-pocion/1.png",
      "Statics/productos/kit-reparacion-profunda-pocion/2.png",
      "Statics/productos/kit-reparacion-profunda-pocion/3.png",
      "Statics/productos/kit-reparacion-profunda-pocion/4.png",
      "Statics/productos/kit-reparacion-profunda-pocion/5.png",
      "Statics/productos/kit-reparacion-profunda-pocion/6.png",
    ],
    short: "El sistema completo de 5 pasos para restaurar cabello seco, maltratado o procesado químicamente.",
    desc: "El sistema completo para restaurar, fortalecer y devolverle la vida al cabello dañado por tintes, decoloraciones, plancha o sol. Incluye Shampoo La Poción (450 ml, limpieza suave sin resecar), Acondicionador La Poción (450 ml), Tratamiento Renovador (450 ml, nutrición profunda), Mascarilla Ancestral (350 ml, con vitaminas A, B1, B2, B6, B12, C y E) y el Óleo B8 Brillo Infinito (aceite ligero que nutre, ilumina y protege). Actúa desde el interior de la fibra para mejorar elasticidad, suavidad y resistencia, sellando la cutícula contra el frizz y la porosidad.",
    benefits: ["Repara el daño profundo de tintes, decoloración y calor", "Fortalece la fibra y evita la ruptura", "Hidratación intensa con brillo sin sensación pesada", "Sella la cutícula: menos frizz y porosidad", "Rutina completa de 5 pasos con envío gratis"],
    howto: "Lava con el Shampoo La Poción y aplica el Acondicionador; enjuaga. Usa el Tratamiento Renovador 2-3 veces por semana y la Mascarilla Ancestral 1-2 veces por semana dejándola actuar 10-15 minutos. Finaliza con unas gotas del Óleo B8 sobre cabello húmedo o seco.",
    ingredients: "Mascarilla Ancestral con vitaminas A, B1, B2, B6, B12, C y E. Consulta la etiqueta de cada producto Poción del kit para la lista completa. Uso externo.",
  },
  {
    id: "kit-rizos-la-pocion",
    dropiId: "1893635", // ID en el catálogo de Dropi (SKU KIT-00085, proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit para Rizos Tongolé «La Poción»",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado"],
    price: 189900,
    cost: 129865,
    size: "4 productos",
    rating: 5.0,
    reviews: 0,
    badge: "Envío gratis",
    badgeClass: "badge-pink",
    art: "kit",
    images: [
      "Statics/productos/kit-rizos-la-pocion/1.jpeg",
      "Statics/productos/kit-rizos-la-pocion/2.jpeg",
      "Statics/productos/kit-rizos-la-pocion/3.jpeg",
      "Statics/productos/kit-rizos-la-pocion/4.jpeg",
      "Statics/productos/kit-rizos-la-pocion/5.jpeg",
      "Statics/productos/kit-rizos-la-pocion/6.jpeg",
      "Statics/productos/kit-rizos-la-pocion/7.jpeg",
    ],
    short: "Shampoo + tratamiento + crema para peinar + mascarilla Tongolé: el sistema completo para rizos 2A a 3C.",
    desc: "El sistema completo para hidratar, definir y restaurar ondas, rizos y crespos (2A a 3C) con acabado natural y libre de frizz. Incluye Shampoo Tongolé (450 ml), Tratamiento Tongolé (450 ml), Crema para Peinar Tongolé (450 ml) y Mascarilla Capilar Tongolé (350 ml): fórmulas nutritivas que reparan la fibra capilar, controlan el frizz y logran rizos definidos por más tiempo, sin sensación pesada.",
    benefits: ["Define y realza ondas y rizos de forma natural", "Controla el frizz incluso en climas húmedos", "Hidratación profunda sin apelmazar", "Repara y fortalece la fibra capilar", "Ideal para cabellos ondulados, rizados y crespos (2A a 3C)"],
    howto: "Lava con el Shampoo Tongolé, aplica el Tratamiento y enjuaga. Usa la Mascarilla 1-2 veces por semana dejándola actuar 10-15 minutos. Finaliza con la Crema para Peinar sobre cabello húmedo y define con tus manos o tu técnica preferida.",
    ingredients: "Consulta la etiqueta de cada producto Tongolé incluido en el kit.",
  },
  {
    id: "kit-rizos-lavado-etniker",
    dropiId: "1979862", // ID en el catálogo de Dropi (SKU KIT-00079, proveedor LIVANA COLOMBIA SAS)
    proveedor: "LIVANA", // bodega Dropi — agrupa órdenes y fletes
    name: "Kit Rizos Lavado Etniker",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado", "afro"],
    price: 109900,
    cost: 65000,
    size: "3 productos",
    rating: 4.9,
    reviews: 0,
    badge: "Nuevo",
    badgeClass: "",
    art: "kitSmall",
    images: [
      "Statics/productos/kit-rizos-lavado-etniker/1.webp",
      "Statics/productos/kit-rizos-lavado-etniker/2.jpg",
      "Statics/productos/kit-rizos-lavado-etniker/3.jpg",
      "Statics/productos/kit-rizos-lavado-etniker/4.jpg",
    ],
    short: "Shampoo + crema para peinar + gel definidora Etniker: tu wash day en 3 pasos (limpia, hidrata, define).",
    desc: "Tu wash day en 3 pasos con Etniker Afro Hair Care: limpia con el Shampoo (250 ml — a elegir entre Nutritivo o Limpieza Profunda anti-residuos), hidrata con la Crema para Peinar Curl Defining (290 g, coco, karité y monoï de Tahití) y define con la Gel Definidora de Rizos (300 g, coco y linaza). Acabado natural, brillo y cero frizz, sin rigidez ni residuos. Ideal para texturas 2B a 4C y cabellos en transición. Escríbenos en las notas del pedido cuál shampoo prefieres; si no nos dices, enviamos el Nutritivo.",
    benefits: ["Definición y moldeo con fijación flexible", "Control del frizz y brillo sin residuos ni pegajosidad", "Hidratación y desenredo sin tirones", "Rutina simple: limpia → hidrata → define", "Fórmulas sin sulfatos, sin siliconas y sin parabenos"],
    howto: "1) Limpia con el shampoo: el Nutritivo para uso frecuente, o el de Limpieza Profunda máximo 2 veces al mes. 2) En cabello húmedo aplica la crema por secciones y activa con scrunch; no enjuagues. 3) Distribuye la gel por secciones, haz scrunch de abajo hacia arriba y seca al aire o con difusor en calor bajo. Refresh día 2-3: humedece ligeramente y aplica una microdosis de gel.",
    ingredients: "Gel: coco y linaza. Crema: coco, karité y monoï de Tahití (con filtro UV). Fórmulas sin sulfatos, sin sal añadida, sin siliconas, sin aceite mineral y libres de parabenos. Uso externo; evitar contacto con los ojos.",
  },
];
