/* ==========================================================================
   Rizos Ondea — Datos de la tienda
   ⚠️ CONFIGURACIÓN: cambia aquí el número de WhatsApp real del negocio.
   ========================================================================== */

const ONDEA_CONFIG = {
  // Número de WhatsApp en formato internacional SIN "+" (57 = Colombia).
  // ⚠️ REEMPLAZAR por el número real del negocio:
  whatsapp: "573000000000",
  ciudad: "Villavicencio",
  envioNacional: 12000,      // COP — envío al resto de Colombia
  envioLocal: 6000,          // COP — envío dentro de Villavicencio
  envioGratisDesde: 150000,  // COP — umbral de envío gratis
};

/* Productos de ejemplo (inventados) mientras llega el catálogo real.
   Categorías: limpieza · hidratacion · definicion · accesorios · kits
   Tipos de rizo: ondulado (2A-2C) · rizado (3A-3C) · afro (4A-4C) */
const ONDEA_PRODUCTS = [
  {
    id: "shampoo-low-poo",
    name: "Shampoo Low Poo «Onda Limpia»",
    category: "limpieza",
    categoryLabel: "Limpieza",
    types: ["ondulado", "rizado", "afro"],
    price: 42900,
    cost: 23500,
    size: "500 ml",
    rating: 4.8,
    reviews: 124,
    badge: "Más vendido",
    badgeClass: "",
    art: "pump",
    short: "Limpieza suave sin sulfatos que respeta el aceite natural de tus rizos.",
    desc: "Shampoo de limpieza suave, libre de sulfatos y sales, formulado para el método curly. Limpia el cuero cabelludo sin resecar la fibra, dejando los rizos suaves, hidratados y listos para definir.",
    benefits: ["Libre de sulfatos, siliconas y parabenos", "Apto para método curly (CG friendly)", "Con aloe vera y agua de coco", "Uso frecuente: no reseca ni esponja"],
    howto: "Aplica sobre el cuero cabelludo húmedo, masajea con las yemas de los dedos y deja que la espuma limpie los largos al enjuagar. Repite si es necesario.",
    ingredients: "Agua, cocamidopropil betaína, aloe barbadensis, agua de coco, glicerina vegetal, pantenol, fragancia hipoalergénica.",
  },
  {
    id: "acondicionador-coco",
    name: "Acondicionador «Nutre & Desenreda» Coco y Karité",
    category: "hidratacion",
    categoryLabel: "Hidratación",
    types: ["ondulado", "rizado", "afro"],
    price: 44900,
    cost: 24900,
    size: "500 ml",
    rating: 4.9,
    reviews: 98,
    badge: null,
    art: "pump",
    short: "Desenreda al instante y aporta la humedad que tu rizo pide a gritos.",
    desc: "Acondicionador cremoso con aceite de coco y manteca de karité que facilita el desenredado, sella la humedad y devuelve la elasticidad a rizos y ondas.",
    benefits: ["Desenredado fácil sin romper el rizo", "Manteca de karité y aceite de coco", "Aporta brillo y elasticidad", "Sin siliconas insolubles"],
    howto: "Después del shampoo, aplica de medios a puntas, desenreda con los dedos o peine de dientes anchos y enjuaga con agua fría para sellar.",
    ingredients: "Agua, alcohol cetílico, manteca de karité, aceite de coco, behentrimonium metosulfato, pantenol, vitamina E.",
  },
  {
    id: "crema-define-rizos",
    name: "Crema para Peinar «Define Rizos»",
    category: "definicion",
    categoryLabel: "Definición",
    types: ["rizado", "afro"],
    price: 38900,
    cost: 19900,
    size: "300 ml",
    rating: 4.9,
    reviews: 156,
    badge: "Favorito",
    badgeClass: "badge-pink",
    art: "tube",
    short: "Definición, control del frizz e hidratación en un solo paso.",
    desc: "Crema de peinado con fijación media que define el patrón natural del rizo, controla el frizz por hasta 48 horas y mantiene la hidratación sin dejar sensación grasosa ni efecto acartonado.",
    benefits: ["Define sin endurecer", "Anti-frizz hasta 48 h", "Con aceite de aguacate y proteína de arroz", "Protección de calor ligera"],
    howto: "Sobre cabello muy húmedo, aplica una cantidad tamaño moneda por sección, distribuye con praying hands y scrunch. Seca al aire o con difusor.",
    ingredients: "Agua, aceite de aguacate, proteína hidrolizada de arroz, glicerina, goma de linaza, manteca de mango, fragancia.",
  },
  {
    id: "gel-cristal",
    name: "Gel Fijador «Cristal de Rizos»",
    category: "definicion",
    categoryLabel: "Definición",
    types: ["ondulado", "rizado", "afro"],
    price: 35900,
    cost: 17900,
    size: "250 ml",
    rating: 4.7,
    reviews: 87,
    badge: null,
    art: "jarGel",
    short: "Fijación fuerte con acabado brillante y cero residuo blanco.",
    desc: "Gel de fijación fuerte que forma un cast protector alrededor de cada rizo para una definición duradera. Se rompe fácil con scrunch y no deja escamas ni residuo blanco.",
    benefits: ["Fijación fuerte de larga duración", "Cast fácil de romper (SOTC)", "Con linaza y pantenol", "No deja residuo ni descama"],
    howto: "Aplica sobre el cabello empapado después de tu crema, con praying hands y scrunch. Cuando seque al 100 %, rompe el cast con un poco de aceite en las manos.",
    ingredients: "Agua, extracto de linaza, glicerina, pantenol, goma xantana, conservante ecocert, fragancia suave.",
  },
  {
    id: "mascarilla-nutritiva",
    name: "Mascarilla «Hidratación Profunda»",
    category: "hidratacion",
    categoryLabel: "Hidratación",
    types: ["rizado", "afro"],
    price: 52900,
    cost: 28900,
    oldPrice: 59900,
    size: "500 g",
    rating: 5.0,
    reviews: 73,
    badge: "Oferta",
    badgeClass: "badge-pink",
    art: "jar",
    short: "Tratamiento intensivo semanal para rizos secos, porosos o teñidos.",
    desc: "Mascarilla de nutrición profunda con triple manteca (karité, cacao y mango) que repara la fibra, reduce la porosidad y devuelve la vida a rizos maltratados por decoloración o calor.",
    benefits: ["Triple manteca: karité, cacao y mango", "Repara puntas abiertas y quebradizas", "Ideal 1 vez por semana", "Apta para cabello teñido o decolorado"],
    howto: "Sobre cabello limpio y húmedo, aplica mechón por mechón, deja actuar 15-20 minutos (con gorro térmico potencia el efecto) y enjuaga muy bien.",
    ingredients: "Agua, manteca de karité, manteca de cacao, manteca de mango, aceite de oliva, queratina vegetal, pantenol.",
  },
  {
    id: "aceite-argan",
    name: "Aceite Sellador «Brillo de Argán»",
    category: "hidratacion",
    categoryLabel: "Hidratación",
    types: ["ondulado", "rizado", "afro"],
    price: 39900,
    cost: 18500,
    size: "60 ml",
    rating: 4.8,
    reviews: 64,
    badge: null,
    art: "dropper",
    short: "Mezcla ligera de argán y jojoba para sellar, brillar y romper el cast.",
    desc: "Blend de aceites puros de argán y jojoba de rápida absorción. Sella la hidratación, aporta brillo espejo y es perfecto para romper el cast del gel sin generar frizz.",
    benefits: ["Argán y jojoba 100 % puros", "Sella puntas y evita resequedad", "Brillo sin efecto grasoso", "Ideal para SOTC y retoques"],
    howto: "Aplica 2-4 gotas en las palmas y sella de medios a puntas sobre cabello húmedo o seco. Úsalo también para romper el cast del gel.",
    ingredients: "Aceite de argán, aceite de jojoba, vitamina E, aceite esencial de vainilla.",
  },
  {
    id: "leave-in-rizos-vivos",
    name: "Leave-In «Rizos Vivos»",
    category: "hidratacion",
    categoryLabel: "Hidratación",
    types: ["ondulado", "rizado"],
    price: 36900,
    cost: 18900,
    size: "250 ml",
    rating: 4.7,
    reviews: 59,
    badge: null,
    art: "spray",
    short: "Hidratación diaria sin enjuague para refrescar y revivir tus rizos.",
    desc: "Crema ligera sin enjuague que hidrata, desenreda y protege durante el día. Perfecta para el refresh de rizos entre lavados: revive la definición sin apelmazar.",
    benefits: ["Hidratación diaria sin enjuague", "Ideal para refresh entre lavados", "Protege del sol y la humedad", "Fórmula ligera: no apelmaza"],
    howto: "En cabello húmedo o seco, aplica una pequeña cantidad y scrunch para reactivar el rizo. Úsalo a diario o en tu rutina de refresh.",
    ingredients: "Agua, aloe vera, glicerina, aceite de almendras, pantenol, filtro UV, fragancia suave.",
  },
  {
    id: "espuma-onda-ligera",
    name: "Espuma Voluminizadora «Onda Ligera»",
    category: "definicion",
    categoryLabel: "Definición",
    types: ["ondulado"],
    price: 33900,
    cost: 16900,
    size: "200 ml",
    rating: 4.6,
    reviews: 41,
    badge: "Para ondas",
    badgeClass: "",
    art: "foam",
    short: "Volumen y definición con acabado natural para ondas 2A-2C.",
    desc: "Mousse ultraligera creada para cabello ondulado: define la onda, levanta la raíz y aporta cuerpo sin el peso de las cremas densas. Acabado flexible y natural.",
    benefits: ["Diseñada para ondas 2A-2C", "Volumen desde la raíz", "Acabado flexible, no acartona", "Con proteína de trigo"],
    howto: "Sobre cabello húmedo boca abajo, aplica 2-3 pumps de espuma con scrunch desde las puntas hacia la raíz. Seca con difusor para máximo volumen.",
    ingredients: "Agua, proteína de trigo, pantenol, polímeros de fijación flexible, fragancia.",
  },
  {
    id: "kit-rutina-completa",
    name: "Kit Rutina Completa «Ondea Full»",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado", "afro"],
    price: 149900,
    cost: 86200,
    oldPrice: 179900,
    size: "4 productos",
    rating: 5.0,
    reviews: 112,
    badge: "Envío gratis",
    badgeClass: "badge-pink",
    art: "kit",
    short: "Shampoo + acondicionador + crema + gel: la rutina curly completa con descuento.",
    desc: "Todo lo que necesitas para tu rutina curly en un solo kit: Shampoo Onda Limpia, Acondicionador Nutre & Desenreda, Crema Define Rizos y Gel Cristal de Rizos. Ahorra $30.000 frente a comprarlos por separado, con envío gratis a toda Colombia.",
    benefits: ["Rutina completa en 4 pasos", "Ahorras $30.000", "Envío gratis a toda Colombia", "Ideal para empezar el método curly"],
    howto: "Lava con el shampoo, desenreda con el acondicionador, define con la crema sobre cabello muy húmedo y sella con el gel. Seca al aire o con difusor.",
    ingredients: "Ver la descripción de cada producto incluido en el kit.",
  },
  {
    id: "gorro-saten",
    name: "Gorro de Satén «Buenas Noches, Rizos»",
    category: "accesorios",
    categoryLabel: "Accesorios",
    types: ["ondulado", "rizado", "afro"],
    price: 25900,
    cost: 9900,
    size: "Talla única",
    rating: 4.9,
    reviews: 203,
    badge: null,
    art: "bonnet",
    short: "Protege tu definición mientras duermes y amanece con rizos intactos.",
    desc: "Gorro de satén premium con banda elástica cómoda que no marca la frente. Evita el frizz y la fricción con la almohada para que tu definición dure más días.",
    benefits: ["Satén suave de alta calidad", "Elástico cómodo que no aprieta", "Reduce frizz y quiebre nocturno", "Alarga la vida de tu definición"],
    howto: "Recoge tus rizos en piña (pineapple) y cúbrelos con el gorro antes de dormir. Lávalo a mano cada semana.",
    ingredients: "95 % satén de poliéster, 5 % elastano.",
  },
  {
    id: "toalla-microfibra",
    name: "Toalla de Microfibra «Seca sin Frizz»",
    category: "accesorios",
    categoryLabel: "Accesorios",
    types: ["ondulado", "rizado", "afro"],
    price: 29900,
    cost: 12500,
    size: "60 × 40 cm",
    rating: 4.8,
    reviews: 88,
    badge: null,
    art: "towel",
    short: "Absorbe el exceso de agua sin alterar el patrón de tu rizo.",
    desc: "Toalla de microfibra ultra absorbente y suave que retira el exceso de agua con plopping o scrunch sin generar frizz ni deformar el rizo, a diferencia de la toalla de algodón.",
    benefits: ["Microfibra ultra suave", "Ideal para plopping", "Seca más rápido sin frizz", "Con botón para sujetarla"],
    howto: "Después de aplicar tus productos, haz scrunch suave o envuelve el cabello en plopping por 10-15 minutos antes de difusar.",
    ingredients: "80 % poliéster, 20 % poliamida (microfibra).",
  },
  {
    id: "difusor-universal",
    name: "Difusor Universal Plegable",
    category: "accesorios",
    categoryLabel: "Accesorios",
    types: ["ondulado", "rizado", "afro"],
    price: 45900,
    cost: 22900,
    size: "Universal",
    rating: 4.6,
    reviews: 35,
    badge: null,
    art: "diffuser",
    short: "Seca con volumen y definición; se pliega para viajar.",
    desc: "Difusor de silicona plegable que se adapta a casi cualquier secadora. Distribuye el aire de forma uniforme para secar tus rizos con volumen, definición y sin frizz. Perfecto para viajes.",
    benefits: ["Compatible con la mayoría de secadoras", "Silicona plegable: ocupa mínimo espacio", "Secado uniforme sin frizz", "Dedos largos para levantar la raíz"],
    howto: "Ajústalo a tu secadora, usa temperatura media y seca por secciones llevando el rizo hacia la raíz. Termina con aire frío para fijar.",
    ingredients: "Silicona de grado alimenticio resistente al calor.",
  },
  {
    id: "kit-refresh",
    name: "Kit Refresh «Rizos de Lunes a Viernes»",
    category: "kits",
    categoryLabel: "Kits",
    types: ["ondulado", "rizado", "afro"],
    price: 69900,
    cost: 47300,
    oldPrice: 76800,
    size: "2 productos + gorro",
    rating: 4.8,
    reviews: 47,
    badge: "Nuevo",
    badgeClass: "",
    art: "kitSmall",
    short: "Leave-in + aceite sellador + gorro de satén para mantener la definición toda la semana.",
    desc: "El combo para que tu wash day rinda toda la semana: Leave-In Rizos Vivos para refrescar, Aceite Brillo de Argán para sellar y gorro de satén para proteger de noche.",
    benefits: ["Mantiene la definición entre lavados", "3 productos con descuento", "Ideal para llevar de viaje", "El regalo perfecto para una curly"],
    howto: "De noche protege con el gorro; en la mañana refresca con el leave-in, scrunch y sella puntas con 2 gotas de aceite.",
    ingredients: "Ver la descripción de cada producto incluido en el kit.",
  },
];
